#!/usr/bin/env python3

import sys
import os
import helpers
from termcolor import colored
from analyzer import Analyzer


def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage : ./tweets @screen_name")
        
    # query for user tweets
    num_tweets = 50
    tweets =  helpers.get_user_timeline(sys.argv[1].strip("@"), num_tweets)
    if (tweets == None):
        sys.exit("Screen name does not exist")
    
    # instantiate Analyzer object
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)
    
    # analyzes the sentiments of each tweets and prints colored
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0 :
            print(colored("{:2d} {}".format(score, tweet), "green"))
        elif score < 0.0 :
            print(colored("{:2d} {}".format(score, tweet), "red"))
        else :
            print(colored("{:2d} {}".format(score, tweet), "yellow"))
        
if __name__ == "__main__":
    main()
